"""add findings and identities tables

Revision ID: 3c396ebbdca2
Revises: cd8cefb0380d
Create Date: 2026-09-24 22:16:55.081392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c396ebbdca2'
down_revision: Union[str, Sequence[str], None] = 'cd8cefb0380d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=False),
    sa.Column('identity_exposure_score', sa.Float(), nullable=False),
    sa.Column('graph_proximity_score', sa.Float(), nullable=False),
    sa.Column('betweenness_centrality', sa.Float(), nullable=False),
    sa.Column('unified_risk_score', sa.Float(), nullable=False),
    sa.Column('hops_to_domain_admin', sa.Integer(), nullable=True),
    sa.Column('attack_path', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_owner'), 'findings', ['owner'], unique=False)
    op.create_index(op.f('ix_findings_unified_risk_score'), 'findings', ['unified_risk_score'], unique=False)
    op.create_table('identities',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('privilege_level', sa.String(length=32), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_days_ago', sa.Integer(), nullable=False),
    sa.Column('owned_asset_ip', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_identities_owned_asset_ip'), 'identities', ['owned_asset_ip'], unique=False)
    op.create_index(op.f('ix_identities_privilege_level'), 'identities', ['privilege_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_privilege_level'), table_name='identities')
    op.drop_index(op.f('ix_identities_owned_asset_ip'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_findings_unified_risk_score'), table_name='findings')
    op.drop_index(op.f('ix_findings_owner'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
