"""create tickets table

Revision ID: cd8cefb0380d
Revises: 
Create Date: 2026-09-24 20:49:26.810386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8cefb0380d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=False),
    sa.Column('identity_exposure_score', sa.Float(), nullable=False),
    sa.Column('unified_risk_score', sa.Float(), nullable=False),
    sa.Column('attack_path', sa.JSON(), nullable=False),
    sa.Column('hops_to_domain_admin', sa.Integer(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_cve_id'), 'tickets', ['cve_id'], unique=False)
    op.create_index(op.f('ix_tickets_owner'), 'tickets', ['owner'], unique=False)
    op.create_index(op.f('ix_tickets_severity'), 'tickets', ['severity'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_unified_risk_score'), 'tickets', ['unified_risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_unified_risk_score'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_severity'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_owner'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_cve_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
